---
- name: "Updating apt repo/cache"
  apt: 
    update_cache: yes
    cache_valid_time: 3600
    upgrade: yes
  
- name: "Installing Packages"
  apt:
    name:
      - awscli
      - cmake
      - covenant-kbx
      - docker.io
      - docker-compose
      - eyewitness
      - gdb
      - gdbserver
      - ghidra
      - gobuster
      - golang
      - keepassxc
      - libreoffice
      - libssl-dev
      - nbtscan-unixwiz
      - ncat
      - nuclei
      - payloadsallthethings
      - peass
      - pipenv
      - python3-pwntools
      - python3-unicorn
      - rlwrap
      - ropper
      - seclists
      - testssl.sh
      - xclip
      - xsel
      - libpcap-dev
      - asleap
      - beef-xss
      - bettercap
      - hcxdumptool
      - hcxtools
      - hostapd
      - hostapd-wpe
      - isc-dhcp-server
      - lighttpd
      - mdk4
      - sslstrip
      - ntpdate
      - flameshot
      - spice-vdagent
      - golang-go
      - feroxbuster
      - rsyslog
      - ufw
      - dconf-cli
      - cargo
      - oscanner
      - tnscmd10g
      - wkhtmltopdf
      - wine64
      - ipcalc
      - terminator
      - fzf
      - highlight
      - eza
      - btop
      - zoxide
      - entr
      - strace
      - ltrace
      - musl-tools
      - remmina
      - obsidian
      - sprayhound
      - libkrb5-dev
    state: latest