---
- name: "Install pipx tools"
  community.general.pipx:
    name: "{{ item.name }}"
    source: "{{ item.source }}"
    state: latest
  loop:
    - { name: 'certipy-ad', source: 'git+https://github.com/ly4k/Certipy.git' }
    - { name: 'autorecon', source: 'git+https://github.com/Tib3rius/AutoRecon.git' }
    - { name: 'roadrecon', source: 'git+https://github.com/dirkjanm/ROADtools.git' }
    - { name: 'mitm6', source: 'git+https://github.com/dirkjanm/mitm6.git' }
    - { name: 'coercer', source: 'git+https://github.com/p0dalirius/Coercer.git'}
    - { name: 'git-dumper', source: 'git+https://github.com/arthaud/git-dumper.git'}
    - { name: 'powerview.py', source: 'git+https://github.com/aniqfakhrul/powerview.py.git'}