---
- name: "Install pipx tools"
  community.general.pipx:
    name: "{{ item.name }}"
    source: "{{ item.url }}"
  loop:
    - { name: 'git-dumper', url: 'git+https://github.com/arthaud/git-dumper.git'}
    - { name: 'powerview.py', url: 'git+https://github.com/aniqfakhrul/powerview.py'}
  ignore_errors: true