[General]
  snippetfile = "/home/kali/.config/pet/snippet.toml"
  editor = "subl"
  column = 40
  selectcmd = "fzf --ansi --exact --layout=reverse --border --height=90% --pointer='>' --cycle --prompt='Snippets> '"
  backend = "gist"
  sortby = ""

[Gist]
  file_name = "pet-snippet.toml"
  access_token = "{{ gist_token }}"
  gist_id = "291e6d868f6435e5ae9123a1ea1026c2"
  public = false
  auto_sync = true

[GitLab]
  file_name = "pet-snippet.toml"
  access_token = ""
  url = ""
  id = ""
  visibility = "private"
  auto_sync = false
  skip_ssl = false
